### ISSUE TITLE
我截取的图片不完整

### ISSUE THREAD

**Issue by sixoneone** [Runjuu/page2image#3]
我运行的 page2image https://www.baoquan.com
截取的图片不完整
我在Windows10上使用的

**Comment by Runjuu** [comment]
please using [template](https://github.com/Runjuu/page2image/blob/master/.github/issue_template.md) to create an new issue and below is my screenshot by using page2image CLI commend. it seems quite complete 🤔
```bash
page2image https://www.baoquan.com/
```
![www baoquan com_](https://user-images.githubusercontent.com/12002941/29965886-1ab281c4-8f42-11e7-84ab-8c3441a67053.png)

**Comment by Runjuu** [comment]
you could just comment below and don't need to create an new issues 😀

#### Node.js & npm version
Node.js: `node -v`;
npm: `npm -v`
#### Operating system:

#### Description of the bug:

#### Example CLI command or javascript code to reproduce the error
```
```

#### Error infos:
```bash
```

**Comment by sixoneone** [comment]
Node.js:  v7.10.0
npm: 4.2.0
Operating system: Windows10
Description of the bug:
![qq 20170901192813](https://user-images.githubusercontent.com/25762884/29968197-20ec8eda-8f4d-11e7-90ca-bb7fea767791.png)
我截取下来的图片：
![www baoquan com](https://user-images.githubusercontent.com/25762884/29968210-292fbcb6-8f4d-11e7-9710-4db4844b4473.png)

**Comment by Runjuu** [comment]
It seems like because this page uses the React framework and the timing of the screenshot is `networkidle` by default. Although the network is idle in this moment, React still have not finished render this page yet.

So there is the problem.

You cloud using below command wait until they rendered the copyright element
```bash
page2image https://www.baoquan.com --sleep=.copyright
```

Or you cloud call page2image via the [Module](https://github.com/Runjuu/page2image#config-) to more accurately determine the timing to take a screenshot
